# Generated by Django 4.1.4 on 2023-01-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='teacher',
            new_name='user',
        ),
    ]
