# Generated by Django 4.1.4 on 2023-01-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_rename_teacher_test_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q_text',
            new_name='text',
        ),
    ]
