# Generated by Django 4.1.4 on 2023-01-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_rename_q_text_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='text',
            field=models.CharField(default='hell', max_length=20),
        ),
    ]
